Jenkinsfile (Declarative Pipeline)
pipeline {
    agent { docker 'hashicorp/packer:1.1.0' }
    stages {
        stage('build') {
            steps {
                sh 'python --version'
            }
        }
    }
}
