---
# defaults file for Delete duplicates

script_name: "harvest-duplicates.py"
script_dir: "/home/{{ ansible_ssh_user }}/harvest_duplicates"
script_path: "{{ script_dir }}/{{ script_name }}"

python_executable_path: /usr/bin/python

datagov_url: "{{ SITE_URL }}"
sysadmin_api_key: "{{ API_KEY }}"
